"""initial schema

Revision ID: 218f1ab1b3ca
Revises: 
Create Date: 2026-09-28 11:56:56.697651
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '218f1ab1b3ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geocode_cache_query_text'), 'geocode_cache', ['query_text'], unique=True)
    op.create_table('osm_pois',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('osm_type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_osm_pois_category'), 'osm_pois', ['category'], unique=False)
    op.create_index(op.f('ix_osm_pois_osm_id'), 'osm_pois', ['osm_id'], unique=False)
    op.create_index(op.f('ix_osm_pois_subcategory'), 'osm_pois', ['subcategory'], unique=False)
    op.create_table('osm_roads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('road_type', sa.String(length=50), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_osm_roads_osm_id'), 'osm_roads', ['osm_id'], unique=False)
    op.create_index(op.f('ix_osm_roads_road_type'), 'osm_roads', ['road_type'], unique=False)
    op.create_table('pincodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pincodes_code'), 'pincodes', ['code'], unique=True)
    op.create_table('savomart_stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('operational', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('pincode_id', sa.Uuid(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('selection_method', sa.String(length=20), nullable=False),
    sa.Column('h3_cells', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pincode_id'], ['pincodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('sub_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_narrative', sa.Text(), nullable=True),
    sa.Column('scouting_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_report_id', sa.Uuid(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('rent_monthly', sa.Float(), nullable=True),
    sa.Column('carpet_area_sqft', sa.Float(), nullable=True),
    sa.Column('frontage_ft', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('building_type', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_report_id'], ['area_reports.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catchment_studies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('area_report_id', sa.Uuid(), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_report_id'], ['area_reports.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('sub_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', sa.String(length=30), nullable=False),
    sa.Column('to_stage', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catchment_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('total_roads_surveyed', sa.Integer(), nullable=False),
    sa.Column('total_roads_in_area', sa.Integer(), nullable=False),
    sa.Column('completion_pct', sa.Float(), nullable=False),
    sa.Column('aggregated_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['catchment_studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('zone_h3_cells', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('zone_boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['catchment_studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lane_surveys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('road_id', sa.Uuid(), nullable=True),
    sa.Column('road_segment', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('household_type', sa.String(length=50), nullable=True),
    sa.Column('household_count_range', sa.String(length=20), nullable=True),
    sa.Column('shop_count', sa.Integer(), nullable=True),
    sa.Column('shop_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('road_condition', sa.String(length=50), nullable=True),
    sa.Column('foot_traffic', sa.String(length=20), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['survey_assignments.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['osm_roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lane_surveys')
    op.drop_table('survey_assignments')
    op.drop_table('catchment_insights')
    op.drop_table('property_history')
    op.drop_table('property_evaluations')
    op.drop_table('catchment_studies')
    op.drop_table('properties')
    op.drop_table('area_reports')
    op.drop_table('areas')
    op.drop_table('users')
    op.drop_table('savomart_stores')
    op.drop_index(op.f('ix_pincodes_code'), table_name='pincodes')
    op.drop_table('pincodes')
    op.drop_index(op.f('ix_osm_roads_road_type'), table_name='osm_roads')
    op.drop_index(op.f('ix_osm_roads_osm_id'), table_name='osm_roads')
    op.drop_table('osm_roads')
    op.drop_index(op.f('ix_osm_pois_subcategory'), table_name='osm_pois')
    op.drop_index(op.f('ix_osm_pois_osm_id'), table_name='osm_pois')
    op.drop_index(op.f('ix_osm_pois_category'), table_name='osm_pois')
    op.drop_table('osm_pois')
    op.drop_index(op.f('ix_geocode_cache_query_text'), table_name='geocode_cache')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
