"""add scouting_tasks table

Revision ID: aa6b3021cbd6
Revises: 218f1ab1b3ca
Create Date: 2026-09-29 06:04:46.040134
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa6b3021cbd6'
down_revision: Union[str, None] = '218f1ab1b3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scouting_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('area_report_id', sa.Uuid(), nullable=True),
    sa.Column('pincode_code', sa.String(length=10), nullable=False),
    sa.Column('hotspot_rank', sa.Integer(), nullable=False),
    sa.Column('hotspot_geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('hotspot_centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('hotspot_score', sa.Integer(), nullable=False),
    sa.Column('hotspot_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['area_report_id'], ['area_reports.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scouting_tasks_assigned_to', 'scouting_tasks', ['assigned_to'])
    op.create_index('idx_scouting_tasks_status', 'scouting_tasks', ['status'])
    op.create_index('idx_scouting_tasks_pincode', 'scouting_tasks', ['pincode_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scouting_tasks_pincode', table_name='scouting_tasks')
    op.drop_index('idx_scouting_tasks_status', table_name='scouting_tasks')
    op.drop_index('idx_scouting_tasks_assigned_to', table_name='scouting_tasks')
    op.drop_table('scouting_tasks')
    # ### end Alembic commands ###
